chore: Update Node.js workflow to use yarn instead of npm

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -19,22 +19,22 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
-    # - name: Use Node.js ${{ matrix.node-version }}
-    #   uses: actions/setup-node@v3
-    #   with:
-    #     node-version: ${{ matrix.node-version }}
-    #     cache: 'yarn'
-    # - run: yarn install
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@v3
+      with:
+        node-version: ${{ matrix.node-version }}
+        cache: 'yarn'
+    - run: yarn install
 
-    # - name: Check if PM2 is installed
-    #   run: |
-    #     if ! command -v pm2 &> /dev/null
-    #     then
-    #         echo "PM2 could not be found, installing..."
-    #         yarn global add pm2
-    #     else
-    #         echo "PM2 is already installed"
-    #     fi
+    - name: Check if PM2 is installed
+      run: |
+        if ! command -v pm2 &> /dev/null
+        then
+            echo "PM2 could not be found, installing..."
+            yarn global add pm2
+        else
+            echo "PM2 is already installed"
+        fi
 
     - name: Start or Restart PM2 Application
       run: |
